server:
  port: 8484

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: "health"

spring:
  application:
    name: Bulk Scan CCD Event Handler Sample Application
  config:
    import: "optional:configtree:/mnt/secrets/bulk-scan/"

idam:
  s2s-auth:
    url:    ${S2S_URL:http://localhost:4552}

allowed-services: bulk_scan_processor,bulk_scan_orchestrator,bulk_scan_sample_app_tests

springdoc:
  packagesToScan: uk.gov.hmcts.reform.bulkscanccdeventhandler
  pathsToMatch: /**
