server:
  port: 8484

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Bulk Scan CCD Event Handler Sample Application

s2s:
  url:    ${S2S_URL:http://localhost:4552}
  secret: ${S2S_SECRET:AAAAAAAAAAAAAAAA}
  name:   ${S2S_NAME:bulk_scan_ccd_sample_app}
