apiVersion: v2
name: bulk-scan-sample-app
home: https://github.com/hmcts/bulk-scan-ccd-event-handler-sample-app
version: 1.3.1
description: HMCTS Bulk Scan CCD event handler application
maintainers:
  - name: HMCTS BSP Team
    email: bspteam@hmcts.net
dependencies:
  - name: java
    version: 3.6.0
    repository: '@hmctspublic'
