java:
  applicationPort: 8484
  environment:
    S2S_NAME: "bulk_scan_ccd_sample_app"

  image: 'https://hmctspublic.azurecr.io/bulk-scan/sample-app:latest'

  keyVaults:
    "s2s":
      resourceGroup: rpe-service-auth-provider
      secrets:
        - microservicekey-bulk-scan-sample-app-tests
